### ISSUE TITLE
Some help pages have content and formatting issues

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1935]
## TODO

- [x] The following cantilever beam help page has issues: [The cantilever beam model](https://openturns.github.io/openturns/latest/usecases/use_case_cantilever_beam.html)

The sentence should not be in bold case.

![image](https://user-images.githubusercontent.com/31351465/155025798-c4bf242c-0690-4af8-821a-7b149c7e1a00.png)

Anne Dutfoy

Edit (30/03/2023). Attempt to fix this bug in PR #2262 (but seem to failed?).

- [x] The [importance_form](http://openturns.github.io/openturns/latest/theory/reliability_sensitivity/importance_form.html) theory help page has a blank space.

![image](https://user-images.githubusercontent.com/31351465/218273254-40e72252-8b95-46cc-a21a-dad13f876b3a.png)

The variables E and F_1, ..., F_n are undefined before or after Y* is suddenly introduced:

![image](https://user-images.githubusercontent.com/31351465/218273499-f5e74fc3-35d4-4b3c-b728-0fd91f64d03f.png)

The variable \tilde{g} is undefined:

![image](https://user-images.githubusercontent.com/31351465/218273845-fbdb1261-369c-4ac9-8536-c4e878adbb66.png)

I assume that this is the linear model which approximates g in the standard space, but this is undefined in the text. 

Anne Dutfoy

Edit (30/03/2023). Attempt to fix in PR #2262.

- [x] The following help page has issues: [Polynomial chaos graphs](http://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_graphs.html)

The following sentences has no meaning.

![image](https://user-images.githubusercontent.com/31351465/146645555-9e98b122-1cec-4f76-9cab-4f40b77de7b4.png)

~~Loic Brevault~~

- [ ] The following page has issues: [Polynomial chaos over database](http://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_database.html)

The following sentence is not formatted.

![image](https://user-images.githubusercontent.com/31351465/146645399-78c4e26e-1deb-4e4f-bc9f-ff4c5c00a9d4.png)

The following sentence has no capital letter, and no point.

![image](https://user-images.githubusercontent.com/31351465/146645421-e0361b28-a7bf-486f-a81d-a3401c195dcd.png)

~~Julien Floquet~~

## Fixed

- [X] [This help page](http://openturns.github.io/openturns/master/theory/meta_modeling/cross_validation.html)

has a formatting issue:

![image](https://user-images.githubusercontent.com/31351465/146644794-eb6886af-1d5b-4d9a-9009-9f3ed24245e4.png)

The text should not be indented at this point. There are plenty of issues of the same nature in the help page.

~~Roman Sueur~~ Edit (9/02/2023) : the bug is fixed.

- [X] [The following page has issues.](http://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_chaos_ishigami_grouped_indices.html)

The following sentence should end with a point.

![image](https://user-images.githubusercontent.com/31351465/146645502-bcb6ff63-1126-4578-9340-5f38b02ad5c3.png)

~~Kieran Delamotte~~

Fixed at #1966.

- [X] [The following help page has issues.](http://openturns.github.io/openturns/master/auto_meta_modeling/fields_metamodels/plot_karhunenloeve_validation.html)

The following sentence should end with a point.

![image](https://user-images.githubusercontent.com/31351465/146645648-bd6fb691-2edf-4f93-94ec-aac264cef09a.png)

~~Mathieu Balesdent~~

Fixed at #1964.

- [ ] [This help page](http://openturns.github.io/openturns/master/auto_numerical_methods/optimization/plot_minmax_by_random_design.html) has issue.

The following sentence does not end with a point.

![image](https://user-images.githubusercontent.com/31351465/146645927-cdc8b3bc-9f56-4f27-9818-ed9db3526475.png)

~~Jérôme Morio~~

- [X] [This page has issues.](http://openturns.github.io/openturns/master/theory/reliability_sensitivity/design_experiment.html)

The sentence seems to be unfinished.

![image](https://user-images.githubusercontent.com/31351465/146646477-13f4570a-8f93-4a35-9e31-2bfc09792c95.png)

~~Anne Dutfoy~~

Fixed at #1975.

- [X] [The following page has issues.](http://openturns.github.io/openturns/master/theory/data_analysis/metropolis_hastings.html)

There is an unexpected blank space after the first equation. Furthermore, the equation should be split on two lines, so that the formatting is correct when the web page is not set to full screen.

![image](https://user-images.githubusercontent.com/31351465/146646075-9c74d1ae-7f47-4d26-b2dc-6e2c2e8a91df.png)

Mathematical statements should be written with at least a comma and, if required some words.

![image](https://user-images.githubusercontent.com/31351465/146646127-fb32e3e9-b899-4dca-baff-6d1de860defe.png)

The same sentence should write: "for any $A \in \mathcal{A}$, the kernel $K(.,A)$ is measurable;"

~~Merlin Keller~~

Fixed at #1971.

- [X] The following logistic help page has issues: [The logistic model](https://openturns.github.io/openturns/latest/usecases/use_case_logistic.html)

There is an empty blank space in the page.

![image](https://user-images.githubusercontent.com/31351465/155025939-d33b96d2-3d0e-435b-a989-ce634a1a588b.png)

Edit (30/03/2023). The bug has been fixed. 

- [X] The following page has issues : [Copulas](http://openturns.github.io/openturns/master/theory/probabilistic_modeling/copulas.html)

The equation for Vc(B) should be centered and the sign function should also be defined with a centered equation.

![image](https://user-images.githubusercontent.com/31351465/146646261-d601d0c0-59e8-4a9b-b754-d78a93782762.png)

Edit: Joseph Muré fixed that in PR #2258.

- [X] The following kriging help page has issues : [Kriging : propagate uncertainties](https://openturns.github.io/openturns/master/auto_meta_modeling/kriging_metamodel/plot_propagate_kriging_ishigami.html)

The sentence should not be in bold case.

![image](https://user-images.githubusercontent.com/31351465/154932782-c6d6e910-9680-4a27-8e13-71e9fad5cc46.png)

Edit: Joseph Muré fixed that in PR #2258.

- [X] The viscous help page has issues : [A viscous free fall example](https://openturns.github.io/openturns/latest/usecases/use_case_viscous_fall.html)

There is an empty blank space in the page.

![image](https://user-images.githubusercontent.com/31351465/155026068-100a98cf-643d-46b2-8a28-a5b1f2cd518a.png)

Edit (02/06/2023). Fixed in #2236

- [X] The [Compare covariance models](https://openturns.github.io/openturns/latest/auto_probabilistic_modeling/stochastic_processes/plot_gaussian_processes_comparison.html) page has issues. The issues are itemized lists which are wrongly formatted.

First bug:

![image](https://user-images.githubusercontent.com/31351465/191356459-cb85c8ca-7c45-4e12-b92e-e7ce56fb8f22.png)

Second bug:

![image](https://user-images.githubusercontent.com/31351465/191356620-72f38aed-8a0a-438a-bfd3-ec0b405bc05a.png)

Edit (30/03/2023): The second bug was fixed, but the first one is still there. Attempt to fix this bug in #2261.
Edit (04/05/2023): the PR #2261 was merged and the first bug is now fixed.

Antoine Ajenjo

- [X] The [SymbolicFunction](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.SymbolicFunction.html) help page has issues.

![image](https://user-images.githubusercontent.com/31351465/192628521-a60fcac5-00c8-4081-aa2c-924ef958ad96.png)

In linear algebra, the standard notations is to use lower case roman variable name in bold font for vectors and upper case roman variable names for matrices. But "CP" is upper case, which is inconsistent with usual notations. Hence, the variable name "CP" should be changed to, say, "a". Furthermore, the second equation should be properly formatted.

Michaël

Edit (02/06/2023). I fixed that in PR #2236.

- [x] The [AdaptiveStieljesAlgorithm](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.AdaptiveStieltjesAlgorithm.html#openturns.AdaptiveStieltjesAlgorithm) help page has issues:

![image](https://user-images.githubusercontent.com/31351465/216779189-72b814c9-2652-48fe-a583-d6b825900a9e.png)

Michaël Baudin

Edit (30/30/2023). I fixed that in PR #2236.

- [X] The following page has issues: [Taylor decomposition importance factors](http://openturns.github.io/openturns/master/theory/reliability_sensitivity/taylor_importance_factors.html)

There are extra dollars in the sentence. There is an extra space after the equation.

![image](https://user-images.githubusercontent.com/31351465/146646523-77f81ba9-a9ae-4f1d-b591-886f787bc781.png)

The importance factors should not use caligraphic letters, which should be saved for sets. I would rather use $\eta_i$ as in equation 15.11 page 141 in "Sensitivity analysis", Borgonovo, Springer, 2017.

![image](https://user-images.githubusercontent.com/31351465/146646550-cfdfe6d1-bb80-4f93-9ca1-0e7e787984bc.png)

Antoine Ajenjo.

Edit (30/03/2023). Fixed in PR #2261.

- [X] The following page has issues: [Random Mixture: affine combination of independent univariate distributions](http://openturns.github.io/openturns/master/theory/probabilistic_modeling/random_mixture.html)

The following equation is too long. It should be split on two lines so that it can be read when the web browser is not full screen. There is an unncessary "*" in the product. The "i" in the exponential may be the imaginary number, but this is implicit and the text does not specify it.

![image](https://user-images.githubusercontent.com/31351465/146646356-0503fd45-01ec-478c-a2dd-e1b0c6e991a6.png)

Here is the effect when the browser is not full screen.

![image](https://user-images.githubusercontent.com/31351465/146646408-3466ae09-1725-4965-9b3c-9b852c617325.png)

There are several equation with the same issue in the page.

![image](https://user-images.githubusercontent.com/31351465/146646422-4f3ca634-df74-4673-bf75-a47c862635f9.png)

![image](https://user-images.githubusercontent.com/31351465/146646425-d523644b-2132-411a-bac2-8efbe7a24e74.png)

Edit (02/06/2023). Fixed in #1935.

- [X] The following page has issues: [Fejer](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.FejerAlgorithm.html)

![image](https://user-images.githubusercontent.com/31351465/147790585-77c5af29-1166-4e37-a5e0-590f0fe8d526.png)

Edit (02/06/2023). Fixed in #1935.

- [X] The following page has formatting issues: [Metamodel of a field function](http://openturns.github.io/openturns/master/auto_meta_modeling/fields_metamodels/plot_fieldfunction_metamodel.html)

The list is not correctly formatted: either each sentence should end with a point, or each sentence should not begin with a capital letter, and end with a comma.

![image](https://user-images.githubusercontent.com/31351465/146645687-18a4b391-5e30-405b-b1c8-a5b90ed588fd.png)

~~Julien Pelamatti~~

Partial bugfix at #1967 and #1973, but there are bugs left in the page:

![image](https://user-images.githubusercontent.com/31351465/154815774-9ef7ed22-df76-44cc-98e1-03cf2affd38e.png)

Edit (02/06/2023). Fixed in #2236.

- [X] This help page: [Create a linear least squares model](http://openturns.github.io/openturns/master/auto_meta_modeling/general_purpose_metamodels/plot_create_linear_least_squares_model.html) has issues.

There is a missing point at the end of this sentence.

![image](https://user-images.githubusercontent.com/31351465/146645025-364274ab-e4e1-47f8-a06b-10c327ff6e8a.png)

This sentence has no capital letter, and does not finish with a point.

![image](https://user-images.githubusercontent.com/31351465/146645042-07190dc0-e6d7-488d-ad27-b7e13b550e01.png)

~~Elias Fekhari~~

Partial bugfix at #1972. But there are bugs left in the page:

![image](https://user-images.githubusercontent.com/31351465/154815946-8480c04e-c671-4db8-8675-e26cdd9ea4d3.png)

There are several sentences without capital letters and no point in the end:

![image](https://user-images.githubusercontent.com/31351465/154815972-2288de8e-db3b-41fa-884f-2c83f8071707.png)

Edit (02/06/2023): Fixed in #2236.

- [X] This help page has several issues: [Taylor approximations](http://openturns.github.io/openturns/master/auto_meta_modeling/general_purpose_metamodels/plot_taylor_approximation.html)

The first equation is poorly formatted. The "2" should have an index. The extra "*" are unnecessary.

![image](https://user-images.githubusercontent.com/31351465/146645136-e63477eb-50aa-4168-b62a-3d2eb8fa2eb1.png)

The following sentence does not begin with a capital letter and does not finish with a point.

![image](https://user-images.githubusercontent.com/31351465/146645162-ff9e49cd-1131-4340-b8e7-7dc651c19d06.png)

Most of the sentences are written in the same _style_.

~~Vincent Chabridon~~

A partial bugfix was done at #1965 and #1977, but curly braces were ignored:

![image](https://user-images.githubusercontent.com/31351465/154815342-32f937ce-ee06-4f11-bedf-81db56bf0a69.png)

Edit (02/06/2023): Fixed in #2236.

- [X] The following help page has issues: [Polynomial chaos exploitation](http://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_exploitation.html)

The list should finish with a point, not a comma.

![image](https://user-images.githubusercontent.com/31351465/146645278-31c20a0f-3f4a-4179-924d-b30a4285423d.png)

The sentence should begin with a capital letter and finish with a point.

![image](https://user-images.githubusercontent.com/31351465/146645291-bc480413-316b-4445-96ab-3fc725a14844.png)

This sentences has no meaning.

![image](https://user-images.githubusercontent.com/31351465/146645320-3578006e-e3ca-4448-93fd-ec46e14a8d61.png)

The content of the following cell is very long and does not bring any sense.

![image](https://user-images.githubusercontent.com/31351465/146645350-ec3ad157-5b8e-4f4c-b3cc-5742ec90467f.png)

~~Jean Abboud~~

Edit (29/03/2023). @JPelamatti partially fixed that page at commit fffb98b
Edit (02/06/2023): Fixed at #2236.

**Comment by josephmure** [comment]
> A partial bugfix was done at https://github.com/openturns/openturns/pull/1965 and https://github.com/openturns/openturns/pull/1977, but curly braces were ignored:
> ![image](https://user-images.githubusercontent.com/31351465/154815342-32f937ce-ee06-4f11-bedf-81db56bf0a69.png)

@mbaudin47 Actually, this bug was also fixed by @vchabri. Here is what the sentence currently looks like in the doc of the master branch:

![image](https://user-images.githubusercontent.com/31989332/160253718-dc1ddeaf-e42f-4492-bfd6-6d1e0f760507.png)
